version: '3.7'

services:

  pyme:
    build: .
    command: ["python", "mercadolibre/pyme.py"]
    volumes:
      - .:/code
    # environment:
      # - CLIENT_ID=foo
      # - CLIENT_SECRET=bar
      # - USER_ID=123456789